import { notFound } from 'next/navigation'
import { Nav } from '@/components/site/nav'
import { Footer } from '@/components/site/footer'
import { blogPosts } from '@/lib/data'
import { pageMetadata, safeJsonLd, siteUrl } from '@/lib/seo'
export function generateStaticParams(){return blogPosts.map(post=>({slug:post.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) { const {slug}=await params;const post=blogPosts.find(item=>item.slug===slug);return post ? pageMetadata(post.title,post.excerpt,'/blog/'+post.slug,true) : {} }
export default async function BlogArticle({params}:{params:Promise<{slug:string}>}) {
 const {slug}=await params;const post=blogPosts.find(item=>item.slug===slug);if(!post)notFound();
 const related=blogPosts.filter(item=>post.relatedSlugs.includes(item.slug));
 const jsonLd={'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:post.excerpt,url:siteUrl+'/blog/'+post.slug,mainEntityOfPage:siteUrl+'/blog/'+post.slug,image:siteUrl+'/images/social-card.png',inLanguage:'en',articleSection:post.category,wordCount:post.wordCount,author:{'@type':'Organization','@id':siteUrl+'/#organization',name:'Starlight AI'},publisher:{'@id':siteUrl+'/#organization'}};
 return <><Nav/><main className="mx-auto max-w-4xl px-6 pt-40 pb-28"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(jsonLd)}}/><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">{post.category} · {post.readTime}</p><h1 className="font-display mt-6 text-[clamp(2.75rem,7vw,5.5rem)] font-bold leading-none tracking-[-0.04em]">{post.title}</h1><p className="mt-8 text-xl leading-relaxed text-muted-foreground">{post.excerpt}</p><div className="mt-16 space-y-12">{post.sections.map(section=><section key={section.heading} className="border-t border-border pt-8"><h2 className="font-display text-3xl font-bold tracking-tight">{section.heading}</h2><p className="mt-4 text-lg leading-relaxed text-muted-foreground">{section.body}</p></section>)}</div><section className="mt-16 border-t border-border pt-8"><h2 className="font-display text-3xl font-bold">Explore the next step</h2><div className="mt-6 flex flex-col gap-4 text-primary">{post.solutionSlug && <a href={'/solutions/'+post.solutionSlug}>Explore the related industry solution →</a>}<a href="/services">Explore automation services →</a>{related.map(item=><a key={item.slug} href={'/blog/'+item.slug}>{item.title} →</a>)}</div></section><a href="/blog" className="mt-16 inline-block font-semibold text-primary">← Back to all guides</a></main><Footer/></>
}
